# Generated by Django 3.0.2 on 2020-01-18 20:12

from django.db import migrations


def create_innital_base_variables(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.create_superuser("rayancocos@gmail.com", "RayanMotta1234")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_innital_base_variables)]

