# Generated by Django 3.0.2 on 2020-01-18 20:12

from django.db import migrations


def create_innital_base_variables(apps, schema_editor):
    from apps.users.models import User

    User.objects.create_superuser(email="admin@admin.com", password="Admin@@123#")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_innital_base_variables)]

